### ISSUE TITLE
implement ProductList to wrap ProductCard

### ISSUE THREAD

**Issue by panchicore** [LinaAlvarado/miniMarket#1]
nice job.

let's try to modify the code base to work with the following idea:

loo at this https://github.com/LinaAlvarado/miniMarket/blob/master/src/App.jsx#L27

now create a component `ProductList` and place it there instead `ProductCard`, because you want to show a list of products o that URL right?.

### create ProductList component

like `ProductCard` but instead, render a `ProductCard` component here https://github.com/LinaAlvarado/miniMarket/blob/master/src/components/ProductCard.jsx#L31 receive prop product `<ProductCard product={element} />` and it will return the following:

### update ProductCard component

returns this https://github.com/LinaAlvarado/miniMarket/blob/master/src/components/ProductCard.jsx#L31-L60

like this, we start organizing the components, and ProductList will pass down a single product to ProductCard to render it independently.

**Comment by panchicore** [comment]
# git and github basics

for you and me to track in detail what you did about this issue:

- work on a new branch, create a new git branch, and switch to this the branch [(?)](https://www.atlassian.com/git/tutorials/using-branches/git-checkout#:~:text=New%20Branches&text=The%20git%20branch%20command%20can,to%20switch%20to%20that%20branch.)
- commit and push these changes on that branch
- when you think is ready, [create a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) from this branch to main, and paste the link here. 

when we do that, we are showing what we added, edited and deleted on the work, and we will be able to [code review](https://about.gitlab.com/topics/version-control/what-is-code-review/#:~:text=Code%20reviews%2C%20also%20known%20as,developers%20learn%20the%20source%20code.).

**Comment by LinaAlvarado** [comment]
Yep, thank you :D  
It looks more organized this way
I made a [pull request ](https://github.com/LinaAlvarado/miniMarket/pull/2/files)

**Comment by panchicore** [comment]
great
